@startuml
title UC-5-6: Регистрация/Авторизация пользователя в системе лояльности
actor "Пользователь" as U 
participant  "МП" as A 
boundary "Сервис аутентификации" as S
boundary "Сервис отрпавки СМС" as M
dataBase "База данных" as DB 
autonumber "<b>[0]"
activate U  

U->A++: Открыть страницу регистрации/авторизации
return Ответ
U->A++: Передать номер телефона
A->A: Проверка корректности заполненных полей
alt Информация заполнена не корректно
A-->U:Уведомление о некорректном заполнении
else  Информация заполнена корректно

A->S++: Проверить валидность номера
deactivate A

S->DB++: Проверить наличие пользователя в БД

alt Регистрация
DB-->S: Пользователь не найден
DB--
S->S++: Сгенирировать СМС
S->M: Передать СМС-код
S--
S--
M++
M-->U: Код подтверждения
M--
U->A++: Ввести код подтверждения
A->S++: Валидация кода подтверждения
A--
S->S++: Подтверждение
S--
S-->U: Запросить дополнительная данные
U->S: Отправить дополнительная данные
S->S++: Валидация
S--
S->DB++: Добавить клиента
DB-->S: Клиент добавлен
DB--
S-->A++: Успешная регистрация
S--
A-->U: Успешная регистрация
A--
else Авторизация
alt Успешная аутентификация

DB-->S++: Пользователь найден
DB++
DB--
S->S++: Сгенирировать СМС
S->M: Передать СМС-код
S--
S--
M++
M-->U: Код подтверждения
M--
U->A++: Ввести код подтверждения
A->S++: Валидация кода подтверждения
A--
S->S++: Подтверждение
S--
S-->U: Успешная авторизация
else Аутентификация не пройдена
DB-->S++: Пользователь не найден
DB++
DB--
S-->A++:Сообщение об ошибке
S--
A-->U: Уведомить об ошибке 
A--
end
end
@enduml
